Add sign out feature
crystal-community/crystal-ann pull request #17
Opened 2017-07-20 17:36 UTC by hugoabonizio

Closes #12.

WDYT @veelenga?

2017-07-20 19:20 UTC, veelenga requested changes

2017-07-20 19:20 UTC, veelenga commented on src/controllers/sessions_controller.cr
> +    session["user_id"] = "0"
i think the better way would be `session.delete("user_id")`

2017-07-20 19:23 UTC, veelenga commented
wow, looks really good, I like it. Thanks you 👍 
Let's deploy to [staging](https://crystal-ann-staging.herokuapp.com/)

2017-07-21 06:39 UTC, veelenga approved these changes

2017-07-21 06:44 UTC, veelenga commented
I changed that and also updated amber to prevent some bugs with a session. Redeployed. Looks ok to me. What do you think?

2017-07-21 12:06 UTC, hugoabonizio commented
I was having some trouble using ```session.delete("user_id")```, the session wasn't updating, maybe because of the amber version. Sorry for the delay. Now I think it's ready to be merged!

2017-07-21 12:40 UTC, merged

2017-07-21 12:40 UTC, veelenga commented
Thank you 👍