Filter by announcement type
crystal-community/crystal-ann pull request #20
Opened 2017-07-24 19:09 UTC by hugoabonizio

Following the idea from #5, this adds a filter by announcement type when clicking on the tag name.

2017-07-24 20:48 UTC, veelenga requested changes
Thanks a lot for this pull request. I have few comments, but that is mostly matter of style than a required change. 

By the way, can we change `Announcement::TYPES` to

```crystal
  TYPES = {
    0 => "blog_post",
    1 => "project_update",
    2 => "conference",
    3 => "meetup",
    4 => "podcast",
    5 => "screencast",
    6 => "video",
    7 => "other",
  }
```
and just adjust `Announcement#typename`, so we will not need to add `Announcement#typename_underscore` and `Announcement.reverse_typename_underscore` methods?

I created new [Gitter channel](https://gitter.im/veelenga/crystal-ann). Let me know if you need to discuss something...

2017-07-24 20:48 UTC, veelenga commented on src/models/announcement.cr
> +      WHERE (title ILIKE $1 OR description ILIKE $1) #{(type ? "AND type = $4" : "")}
Probably this would be a bit cleaner: `#{"AND type = $4" if type}`

2017-07-24 20:48 UTC, veelenga commented on src/models/announcement.cr
> +    parameters = if type
```crystal
parameters = ["%#{query}%", per_page, (page - 1) * per_page]
parameters << type if type
```

2017-07-24 20:48 UTC, veelenga commented on src/models/announcement.cr
> +    parameters = if type
```crystal
parameters = ["%#{query}%"] of String | Int32
parameters << type if type
```

2017-07-24 20:48 UTC, veelenga commented on src/models/announcement.cr
> +        WHERE (title ILIKE $1 OR description ILIKE $1) #{(type ? "AND type = $2" : "")}
`#{"AND type = $2" if type}`

2017-07-24 20:48 UTC, veelenga commented on src/models/announcement.cr
> +    index
`TYPES.find { |_, type| type.tr(" ", "").underscore == typename }.try &.first`

2017-07-25 12:35 UTC, hugoabonizio commented
You are right! I made the requested changes. What do you think now?

2017-07-25 12:54 UTC, veelenga commented
Looks nice 😻 😼  
I will test it this evening and deploy if everything is fine. Thanks again.

2017-07-25 13:33 UTC, veelenga approved these changes

2017-07-25 16:52 UTC, merged

2017-07-25 17:01 UTC, veelenga commented
Did two small fixed and deployed 👍  

If you plan to continue to work on this project, please let me know the task you are going to do, so we will not do the same job concurrently. See you.

2017-07-25 17:34 UTC, hugoabonizio commented
Thanks! Next time I'll let you know throught the gitter channel :smile: