Added icons and web app manifest
crystal-community/crystal-ann pull request #47
Opened 2017-10-02 21:25 UTC by vaibhavsingh97

Fixes #46

2017-10-02 21:26 UTC, vaibhavsingh97 commented
@veelenga tell me what should i use in start url, i will add it 😄

2017-10-03 07:10 UTC, veelenga commented on manifest.json
> +  "start_url": "",
"start_url":"./",

2017-10-03 07:12 UTC, veelenga requested changes
1. Use `./` as a start url.
2. Remove `related_applications`, since we don't have related native application and it produces a warning. See https://github.com/w3c/manifest/issues/591.
2. Move `launcher-icon/` and `manifest.json` to `public/` folder.
2. Use `portrait` orientation instead of `landscape`
3. Tell the browser about the manifest `link rel="manifest" href="/manifest.json"` in [the layout](https://github.com/vaibhavsingh97/crystal-ann/blob/4fed2a9123c8e7d2e8dd0943850c5b7548d63f46/src/views/layouts/application.slang).

Also be free to add yourself to the list of [contributors](https://github.com/crystal-community/crystal-ann#contributors) ;)

Thanks in advanced

2017-10-03 12:05 UTC, hugoabonizio commented
Another option is to use ```/?utm_source=homescreen``` as ```start_url``` so we can track this with GA as suggested on https://developers.google.com/web/fundamentals/web-app-manifest/?utm_source=devtools

2017-10-03 15:15 UTC, vaibhavsingh97 commented
@veelenga Please review

2017-10-03 15:29 UTC, veelenga approved these changes

2017-10-03 15:32 UTC, veelenga commented
Now this works perfectly in Chrome:

<img width="1436" alt="screen shot 2017-10-03 at 6 31 23 pm" src="https://user-images.githubusercontent.com/3624712/31133809-245f02d4-a869-11e7-911b-426adc4af0c6.png">

Good job. Thanks for contribution!

2017-10-03 15:32 UTC, merged